// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmkkgiachpuuvtwlqlkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRta2tnaWFjaHB1dXZ0d2xxbGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNTQ5OTcsImV4cCI6MjA1MzczMDk5N30.y72s16RpduaOJPQm7n6spLfyDMqNS_520US14btX0wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);